[package]
name = "autoship"
version = "1.0.0"
edition = "2024"
license = "MIT"
description = "From staged changes to pushed code in one command."
repository = "https://github.com/Chitresh-code/autoship"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
comfy-table = "8.0.0"
console = "0.16.6"
dialoguer = "0.12.0"
indicatif = "0.18.6"
semver = "1.0.28"
serde_json = "1.0.151"
toml = "1.1.6"

[dev-dependencies]
assert_cmd = "2.2.2"
